name: C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: fetch dependencies
      run: sudo apt-get install gtest
    - name: prepare build directory
      run: mkdir build && cd build
    - name: configure
      run: cmake ..
    - name: make
      run: make -j${nproc}
    - name: test
      run: ctest -j${nproc}
